{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "781c1110",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "unexpected indent (1960456687.py, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[3], line 2\u001b[1;36m\u001b[0m\n\u001b[1;33m    open_csv(filename='books.csv')\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m unexpected indent\n"
     ]
    }
   ],
   "source": [
    " import csv\n",
    "    open_csv(filename='books.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d7b7f857",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "\n",
    "def open_csv(filename='books.csv'):\n",
    "    with open(filename, 'r') as csv_file:\n",
    "        csv_reader = csv.reader(csv_file)\n",
    "        header = next(csv_reader)\n",
    "        books = []\n",
    "        # Loop over each row in the CSV file\n",
    "        for row in csv_reader:\n",
    "            d = {header[i]: row[i] for i in range(len(header))}\n",
    "            books.append(d)\n",
    "    return books"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e044351c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'titre': 'To Kill a Mockingbird',\n",
       "  'auteur': 'Harper Lee',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1960',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': '1984',\n",
       "  'auteur': 'George Orwell',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1949',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Great Gatsby',\n",
       "  'auteur': 'F. Scott Fitzgerald',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1925',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Catcher in the Rye',\n",
       "  'auteur': 'J.D. Salinger',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1951',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Pride and Prejudice',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1813',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Hobbit',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1937',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Moby Dick',\n",
       "  'auteur': 'Herman Melville',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1851',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '14'},\n",
       " {'titre': 'War and Peace',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'History',\n",
       "  'annee': '1869',\n",
       "  'prix': '18.99',\n",
       "  'quantite': '7'},\n",
       " {'titre': 'Great Expectations',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1861',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Ulysses',\n",
       "  'auteur': 'James Joyce',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1922',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Catch-22',\n",
       "  'auteur': 'Joseph Heller',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1961',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Brave New World',\n",
       "  'auteur': 'Aldous Huxley',\n",
       "  'genre': 'Science Fiction',\n",
       "  'annee': '1932',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Crime and Punishment',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1866',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'Gone with the Wind',\n",
       "  'auteur': 'Margaret Mitchell',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1936',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Odyssey',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '700 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Divine Comedy',\n",
       "  'auteur': 'Dante Alighieri',\n",
       "  'genre': 'Mythology',\n",
       "  'annee': '1320',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Iliad',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '762 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Don Quixote',\n",
       "  'auteur': 'Miguel de Cervantes',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1605',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Adventures of Huckleberry Finn',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1884',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Adventures of Tom Sawyer',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1876',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Picture of Dorian Gray',\n",
       "  'auteur': 'Oscar Wilde',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1890',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Frankenstein',\n",
       "  'auteur': 'Mary Shelley',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1818',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Dracula',\n",
       "  'auteur': 'Bram Stoker',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1897',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Count of Monte Cristo',\n",
       "  'auteur': 'Alexandre Dumas',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1844',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Little Women',\n",
       "  'auteur': 'Louisa May Alcott',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1868',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Sense and Sensibility',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1811',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Wuthering Heights',\n",
       "  'auteur': 'Emily Bronte',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1847',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Old Man and the Sea',\n",
       "  'auteur': 'Ernest Hemingway',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1952',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'One Hundred Years of Solitude',\n",
       "  'auteur': 'Gabriel Garcia Marquez',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1967',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Brothers Karamazov',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1880',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Metamorphosis',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1915',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'David Copperfield',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '18'},\n",
       " {'titre': 'The Trial',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1925',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Madame Bovary',\n",
       "  'auteur': 'Gustave Flaubert',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1856',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'The Stranger',\n",
       "  'auteur': 'Albert Camus',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1942',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'Les MisÃ©rables',\n",
       "  'auteur': 'Victor Hugo',\n",
       "  'genre': 'History',\n",
       "  'annee': '1862',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Scarlet Letter',\n",
       "  'auteur': 'Nathaniel Hawthorne',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'Anna Karenina',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1877',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'A Tale of Two Cities',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'History',\n",
       "  'annee': '1859',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Grapes of Wrath',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'History',\n",
       "  'annee': '1939',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Of Mice and Men',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1937',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Lord of the Rings',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1954',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': \"Alice's Adventures in Wonderland\",\n",
       "  'auteur': 'Lewis Carroll',\n",
       "  'genre': 'Children',\n",
       "  'annee': '1865',\n",
       "  'prix': '8.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': \"Harry Potter and the Philosopher's Stone\",\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1997',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'Harry Potter and the Chamber of Secrets',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1998',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Harry Potter and the Prisoner of Azkaban',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1999',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'The Kite Runner',\n",
       "  'auteur': 'Khaled Hosseini',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2003',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Atonement',\n",
       "  'auteur': 'Ian McEwan',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2001',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Da Vinci Code',\n",
       "  'auteur': 'Dan Brown',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2003',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'The Girl with the Dragon Tattoo',\n",
       "  'auteur': 'Stieg Larsson',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2005',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Hunger Games',\n",
       "  'auteur': 'Suzanne Collins',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2008',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'The Fault in Our Stars',\n",
       "  'auteur': 'John Green',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2012',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'Fifty Shades of Grey',\n",
       "  'auteur': 'E. L. James',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2011',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'The Maze Runner',\n",
       "  'auteur': 'James Dashner',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2009',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Divergent',\n",
       "  'auteur': 'Veronica Roth',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2011',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Gone Girl',\n",
       "  'auteur': 'Gillian Flynn',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2012',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Alchemist',\n",
       "  'auteur': 'Paulo Coelho',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2005',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'A Game of Thrones',\n",
       "  'auteur': 'George R. R. Martin',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2005',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Help',\n",
       "  'auteur': 'Kathryn Stockett',\n",
       "  'genre': 'History',\n",
       "  'annee': '2009',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Girl on the Train',\n",
       "  'auteur': 'Paula Hawkins',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2015',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'Twilight',\n",
       "  'auteur': 'Stephenie Meyer',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2005',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'}]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "open_csv(filename='books.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a3593038",
   "metadata": {},
   "outputs": [],
   "source": [
    "def recherche_titre_auteur(books):\n",
    "    inpt = input(\"donnez un titre ou un auteur\").lower()\n",
    "    output = []\n",
    "    for b in books:\n",
    "        if inpt in b[\"auteur\"].lower():\n",
    "            output.append(b)\n",
    "        elif inpt in b[\"titre\"].lower():\n",
    "            output.append(b)\n",
    "    return output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "40f426ad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "donnez un titre ou un auteurgreat\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "string indices must be integers",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[8], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mrecherche_titre_auteur\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mbooks.csv\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[1;32mIn[6], line 5\u001b[0m, in \u001b[0;36mrecherche_titre_auteur\u001b[1;34m(books)\u001b[0m\n\u001b[0;32m      3\u001b[0m output \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m b \u001b[38;5;129;01min\u001b[39;00m books:\n\u001b[1;32m----> 5\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m inpt \u001b[38;5;129;01min\u001b[39;00m \u001b[43mb\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mauteur\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241m.\u001b[39mlower():\n\u001b[0;32m      6\u001b[0m         output\u001b[38;5;241m.\u001b[39mappend(b)\n\u001b[0;32m      7\u001b[0m     \u001b[38;5;28;01melif\u001b[39;00m inpt \u001b[38;5;129;01min\u001b[39;00m b[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtitre\u001b[39m\u001b[38;5;124m\"\u001b[39m]\u001b[38;5;241m.\u001b[39mlower():\n",
      "\u001b[1;31mTypeError\u001b[0m: string indices must be integers"
     ]
    }
   ],
   "source": [
    "recherche_titre_auteur(\"books.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "cdb61f55",
   "metadata": {},
   "outputs": [],
   "source": [
    "def recherche_titre_auteur(books):\n",
    "    inpt = input(\"donnez un titre ou un auteur\").lower()\n",
    "    output = []\n",
    "    for b in books:\n",
    "        if inpt in b[\"auteur\"].lower():\n",
    "            output.append(b)\n",
    "        elif inpt in b[\"titre\"].lower():\n",
    "            output.append(b)\n",
    "    return output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "83de5b76",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "donnez un titre ou un auteurharper\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "string indices must be integers",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[15], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mrecherche_titre_auteur\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mbooks.csv\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[1;32mIn[14], line 5\u001b[0m, in \u001b[0;36mrecherche_titre_auteur\u001b[1;34m(books)\u001b[0m\n\u001b[0;32m      3\u001b[0m output \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m b \u001b[38;5;129;01min\u001b[39;00m books:\n\u001b[1;32m----> 5\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m inpt \u001b[38;5;129;01min\u001b[39;00m \u001b[43mb\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mauteur\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241m.\u001b[39mlower():\n\u001b[0;32m      6\u001b[0m         output\u001b[38;5;241m.\u001b[39mappend(\u001b[38;5;28mint\u001b[39m(b))\n\u001b[0;32m      7\u001b[0m     \u001b[38;5;28;01melif\u001b[39;00m inpt \u001b[38;5;129;01min\u001b[39;00m b[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtitre\u001b[39m\u001b[38;5;124m\"\u001b[39m]\u001b[38;5;241m.\u001b[39mlower():\n",
      "\u001b[1;31mTypeError\u001b[0m: string indices must be integers"
     ]
    }
   ],
   "source": [
    "recherche_titre_auteur(\"books.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "8a889c20",
   "metadata": {},
   "outputs": [],
   "source": [
    "def recherche_genre(books):\n",
    "    inpt = input(\"Veuillez saisir un genre :\").lower()\n",
    "    output = []\n",
    "    for b in books:\n",
    "        if inpt in b[\"genre\"].lower():\n",
    "            output.append(b)\n",
    "    return output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "637b8797",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Veuillez saisir un genre :fiction\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "string indices must be integers",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[17], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mrecherche_genre\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mbooks.csv\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[1;32mIn[16], line 5\u001b[0m, in \u001b[0;36mrecherche_genre\u001b[1;34m(books)\u001b[0m\n\u001b[0;32m      3\u001b[0m output \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m b \u001b[38;5;129;01min\u001b[39;00m books:\n\u001b[1;32m----> 5\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m inpt \u001b[38;5;129;01min\u001b[39;00m \u001b[43mb\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mgenre\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241m.\u001b[39mlower():\n\u001b[0;32m      6\u001b[0m         output\u001b[38;5;241m.\u001b[39mappend(b)\n\u001b[0;32m      7\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m output\n",
      "\u001b[1;31mTypeError\u001b[0m: string indices must be integers"
     ]
    }
   ],
   "source": [
    "recherche_genre(\"books.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "a043a4d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "\n",
    "def open_csv(filename='books.csv'):\n",
    "    with open(filename, 'r') as csv_file:\n",
    "        csv_reader = csv.reader(csv_file)\n",
    "        header = next(csv_reader)\n",
    "        books = []\n",
    "        # Loop over each row in the CSV file\n",
    "        for row in csv_reader:\n",
    "            d = {header[i]: row[i] for i in range(len(header))}\n",
    "            books.append(d)\n",
    "    return books"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "9d11a5c8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'titre': 'To Kill a Mockingbird',\n",
       "  'auteur': 'Harper Lee',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1960',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': '1984',\n",
       "  'auteur': 'George Orwell',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1949',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Great Gatsby',\n",
       "  'auteur': 'F. Scott Fitzgerald',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1925',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Catcher in the Rye',\n",
       "  'auteur': 'J.D. Salinger',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1951',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Pride and Prejudice',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1813',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Hobbit',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1937',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Moby Dick',\n",
       "  'auteur': 'Herman Melville',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1851',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '14'},\n",
       " {'titre': 'War and Peace',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'History',\n",
       "  'annee': '1869',\n",
       "  'prix': '18.99',\n",
       "  'quantite': '7'},\n",
       " {'titre': 'Great Expectations',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1861',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Ulysses',\n",
       "  'auteur': 'James Joyce',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1922',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Catch-22',\n",
       "  'auteur': 'Joseph Heller',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1961',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Brave New World',\n",
       "  'auteur': 'Aldous Huxley',\n",
       "  'genre': 'Science Fiction',\n",
       "  'annee': '1932',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Crime and Punishment',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1866',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'Gone with the Wind',\n",
       "  'auteur': 'Margaret Mitchell',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1936',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Odyssey',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '700 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Divine Comedy',\n",
       "  'auteur': 'Dante Alighieri',\n",
       "  'genre': 'Mythology',\n",
       "  'annee': '1320',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Iliad',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '762 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Don Quixote',\n",
       "  'auteur': 'Miguel de Cervantes',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1605',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Adventures of Huckleberry Finn',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1884',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Adventures of Tom Sawyer',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1876',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Picture of Dorian Gray',\n",
       "  'auteur': 'Oscar Wilde',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1890',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Frankenstein',\n",
       "  'auteur': 'Mary Shelley',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1818',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Dracula',\n",
       "  'auteur': 'Bram Stoker',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1897',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Count of Monte Cristo',\n",
       "  'auteur': 'Alexandre Dumas',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1844',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Little Women',\n",
       "  'auteur': 'Louisa May Alcott',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1868',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Sense and Sensibility',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1811',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Wuthering Heights',\n",
       "  'auteur': 'Emily Bronte',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1847',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Old Man and the Sea',\n",
       "  'auteur': 'Ernest Hemingway',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1952',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'One Hundred Years of Solitude',\n",
       "  'auteur': 'Gabriel Garcia Marquez',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1967',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Brothers Karamazov',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1880',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Metamorphosis',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1915',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'David Copperfield',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '18'},\n",
       " {'titre': 'The Trial',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1925',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Madame Bovary',\n",
       "  'auteur': 'Gustave Flaubert',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1856',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'The Stranger',\n",
       "  'auteur': 'Albert Camus',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1942',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'Les MisÃ©rables',\n",
       "  'auteur': 'Victor Hugo',\n",
       "  'genre': 'History',\n",
       "  'annee': '1862',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Scarlet Letter',\n",
       "  'auteur': 'Nathaniel Hawthorne',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'Anna Karenina',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1877',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'A Tale of Two Cities',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'History',\n",
       "  'annee': '1859',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Grapes of Wrath',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'History',\n",
       "  'annee': '1939',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Of Mice and Men',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1937',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Lord of the Rings',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1954',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': \"Alice's Adventures in Wonderland\",\n",
       "  'auteur': 'Lewis Carroll',\n",
       "  'genre': 'Children',\n",
       "  'annee': '1865',\n",
       "  'prix': '8.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': \"Harry Potter and the Philosopher's Stone\",\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1997',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'Harry Potter and the Chamber of Secrets',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1998',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Harry Potter and the Prisoner of Azkaban',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1999',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'The Kite Runner',\n",
       "  'auteur': 'Khaled Hosseini',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2003',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Atonement',\n",
       "  'auteur': 'Ian McEwan',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2001',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Da Vinci Code',\n",
       "  'auteur': 'Dan Brown',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2003',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'The Girl with the Dragon Tattoo',\n",
       "  'auteur': 'Stieg Larsson',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2005',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Hunger Games',\n",
       "  'auteur': 'Suzanne Collins',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2008',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'The Fault in Our Stars',\n",
       "  'auteur': 'John Green',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2012',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'Fifty Shades of Grey',\n",
       "  'auteur': 'E. L. James',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2011',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'The Maze Runner',\n",
       "  'auteur': 'James Dashner',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2009',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Divergent',\n",
       "  'auteur': 'Veronica Roth',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2011',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Gone Girl',\n",
       "  'auteur': 'Gillian Flynn',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2012',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Alchemist',\n",
       "  'auteur': 'Paulo Coelho',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2005',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'A Game of Thrones',\n",
       "  'auteur': 'George R. R. Martin',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2005',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Help',\n",
       "  'auteur': 'Kathryn Stockett',\n",
       "  'genre': 'History',\n",
       "  'annee': '2009',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Girl on the Train',\n",
       "  'auteur': 'Paula Hawkins',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2015',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'Twilight',\n",
       "  'auteur': 'Stephenie Meyer',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2005',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'}]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "open_csv(filename='books.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "49fc88a1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'titre': 'To Kill a Mockingbird',\n",
       "  'auteur': 'Harper Lee',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1960',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': '1984',\n",
       "  'auteur': 'George Orwell',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1949',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Great Gatsby',\n",
       "  'auteur': 'F. Scott Fitzgerald',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1925',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Catcher in the Rye',\n",
       "  'auteur': 'J.D. Salinger',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1951',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Pride and Prejudice',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1813',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Hobbit',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1937',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Moby Dick',\n",
       "  'auteur': 'Herman Melville',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1851',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '14'},\n",
       " {'titre': 'War and Peace',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'History',\n",
       "  'annee': '1869',\n",
       "  'prix': '18.99',\n",
       "  'quantite': '7'},\n",
       " {'titre': 'Great Expectations',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1861',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Ulysses',\n",
       "  'auteur': 'James Joyce',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1922',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Catch-22',\n",
       "  'auteur': 'Joseph Heller',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1961',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Brave New World',\n",
       "  'auteur': 'Aldous Huxley',\n",
       "  'genre': 'Science Fiction',\n",
       "  'annee': '1932',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Crime and Punishment',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1866',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'Gone with the Wind',\n",
       "  'auteur': 'Margaret Mitchell',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1936',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Odyssey',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '700 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Divine Comedy',\n",
       "  'auteur': 'Dante Alighieri',\n",
       "  'genre': 'Mythology',\n",
       "  'annee': '1320',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'The Iliad',\n",
       "  'auteur': 'Homer',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '762 BC',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Don Quixote',\n",
       "  'auteur': 'Miguel de Cervantes',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1605',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Adventures of Huckleberry Finn',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1884',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Adventures of Tom Sawyer',\n",
       "  'auteur': 'Mark Twain',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1876',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Picture of Dorian Gray',\n",
       "  'auteur': 'Oscar Wilde',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1890',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '8'},\n",
       " {'titre': 'Frankenstein',\n",
       "  'auteur': 'Mary Shelley',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1818',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Dracula',\n",
       "  'auteur': 'Bram Stoker',\n",
       "  'genre': 'Horror',\n",
       "  'annee': '1897',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Count of Monte Cristo',\n",
       "  'auteur': 'Alexandre Dumas',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1844',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Little Women',\n",
       "  'auteur': 'Louisa May Alcott',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1868',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'Sense and Sensibility',\n",
       "  'auteur': 'Jane Austen',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1811',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Wuthering Heights',\n",
       "  'auteur': 'Emily Bronte',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1847',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'The Old Man and the Sea',\n",
       "  'auteur': 'Ernest Hemingway',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '1952',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'One Hundred Years of Solitude',\n",
       "  'auteur': 'Gabriel Garcia Marquez',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1967',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'The Brothers Karamazov',\n",
       "  'auteur': 'Fyodor Dostoevsky',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1880',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Metamorphosis',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1915',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'David Copperfield',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '18'},\n",
       " {'titre': 'The Trial',\n",
       "  'auteur': 'Franz Kafka',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '1925',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'Madame Bovary',\n",
       "  'auteur': 'Gustave Flaubert',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1856',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '12'},\n",
       " {'titre': 'The Stranger',\n",
       "  'auteur': 'Albert Camus',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1942',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'Les MisÃ©rables',\n",
       "  'auteur': 'Victor Hugo',\n",
       "  'genre': 'History',\n",
       "  'annee': '1862',\n",
       "  'prix': '17.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Scarlet Letter',\n",
       "  'auteur': 'Nathaniel Hawthorne',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1850',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '25'},\n",
       " {'titre': 'Anna Karenina',\n",
       "  'auteur': 'Leo Tolstoy',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '1877',\n",
       "  'prix': '16.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': 'A Tale of Two Cities',\n",
       "  'auteur': 'Charles Dickens',\n",
       "  'genre': 'History',\n",
       "  'annee': '1859',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '20'},\n",
       " {'titre': 'The Grapes of Wrath',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'History',\n",
       "  'annee': '1939',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '10'},\n",
       " {'titre': 'Of Mice and Men',\n",
       "  'auteur': 'John Steinbeck',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '1937',\n",
       "  'prix': '9.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Lord of the Rings',\n",
       "  'auteur': 'J.R.R. Tolkien',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1954',\n",
       "  'prix': '20.99',\n",
       "  'quantite': '15'},\n",
       " {'titre': \"Alice's Adventures in Wonderland\",\n",
       "  'auteur': 'Lewis Carroll',\n",
       "  'genre': 'Children',\n",
       "  'annee': '1865',\n",
       "  'prix': '8.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': \"Harry Potter and the Philosopher's Stone\",\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1997',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'Harry Potter and the Chamber of Secrets',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1998',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Harry Potter and the Prisoner of Azkaban',\n",
       "  'auteur': 'J.K. Rowling',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '1999',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'The Kite Runner',\n",
       "  'auteur': 'Khaled Hosseini',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2003',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Atonement',\n",
       "  'auteur': 'Ian McEwan',\n",
       "  'genre': 'Fiction',\n",
       "  'annee': '2001',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Da Vinci Code',\n",
       "  'auteur': 'Dan Brown',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2003',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'The Girl with the Dragon Tattoo',\n",
       "  'auteur': 'Stieg Larsson',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2005',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Hunger Games',\n",
       "  'auteur': 'Suzanne Collins',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2008',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'The Fault in Our Stars',\n",
       "  'auteur': 'John Green',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2012',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'},\n",
       " {'titre': 'Fifty Shades of Grey',\n",
       "  'auteur': 'E. L. James',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2011',\n",
       "  'prix': '11.99',\n",
       "  'quantite': '60'},\n",
       " {'titre': 'The Maze Runner',\n",
       "  'auteur': 'James Dashner',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2009',\n",
       "  'prix': '10.99',\n",
       "  'quantite': '45'},\n",
       " {'titre': 'Divergent',\n",
       "  'auteur': 'Veronica Roth',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2011',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '55'},\n",
       " {'titre': 'Gone Girl',\n",
       "  'auteur': 'Gillian Flynn',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2012',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Alchemist',\n",
       "  'auteur': 'Paulo Coelho',\n",
       "  'genre': 'Adventure',\n",
       "  'annee': '2005',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'A Game of Thrones',\n",
       "  'auteur': 'George R. R. Martin',\n",
       "  'genre': 'Fantasy',\n",
       "  'annee': '2005',\n",
       "  'prix': '15.99',\n",
       "  'quantite': '35'},\n",
       " {'titre': 'The Help',\n",
       "  'auteur': 'Kathryn Stockett',\n",
       "  'genre': 'History',\n",
       "  'annee': '2009',\n",
       "  'prix': '14.99',\n",
       "  'quantite': '30'},\n",
       " {'titre': 'The Girl on the Train',\n",
       "  'auteur': 'Paula Hawkins',\n",
       "  'genre': 'Mystery',\n",
       "  'annee': '2015',\n",
       "  'prix': '13.99',\n",
       "  'quantite': '40'},\n",
       " {'titre': 'Twilight',\n",
       "  'auteur': 'Stephenie Meyer',\n",
       "  'genre': 'Romance',\n",
       "  'annee': '2005',\n",
       "  'prix': '12.99',\n",
       "  'quantite': '50'}]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "books = open_csv()\n",
    "books"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "67146302",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "61"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(books)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2dcfcb22",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
